{% set name = "coqui-trainer" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coqui_trainer-{{ version }}.tar.gz
  sha256: 37cfab2462f5b97195ae8efdb7441adf17bda7e4faa2d243b1c31ba5562f4d42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<3.10
  run:
    - coqpit
    - fsspec
    - pysoundfile
    - python >=3.6,<3.10
    - pytorch >=1.7
    - tensorboardx

test:
  imports:
    - trainer
    - trainer.logging
    - trainer.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/coqui-ai/Trainer
  summary: Flexible general purpose model trainer for PyTorch
  license: Apache-2.0
  # PR Need to be made upstream to bundle in license
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
